name: resume_master
services:
  db:
    container_name: database
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    env_file:
      - "./www/.env"
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
      # - "./db/data:/var/lib/mysql"
    networks:
      - app-net
  www:
    depends_on:
      - db
    build: .
    container_name: web_server
    image: php:8.3.4RC1-apache-bookworm
    restart: always
    volumes:
      - "./www/:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
